name: Code Foundry

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  actions: write
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  release:
    name: Release
    uses: 0xPlayerOne/code-foundry/.github/workflows/release.yml@3c8eeb29b2984e98e2604fbb6a86d3df72f1c0b2
    with:
      runner: ubuntu-slim
      runtime-repository: 0xPlayerOne/code-foundry
      runtime-ref: 3c8eeb29b2984e98e2604fbb6a86d3df72f1c0b2
    secrets: inherit
