name: Code Foundry

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [staging]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Test
    uses: 0xPlayerOne/code-foundry/.github/workflows/test.yml@3c8eeb29b2984e98e2604fbb6a86d3df72f1c0b2
    with:
      runtime-repository: 0xPlayerOne/code-foundry
      runtime-ref: 3c8eeb29b2984e98e2604fbb6a86d3df72f1c0b2
      runner: ubuntu-latest
      unit-runner: ubuntu-slim
    secrets: inherit
